routes:
  - route: "^.+\\.(js|css|svg|woff(2)?)$"
    headers:
      Cache-Control: 'public, max-age=31536000, immutable'
  - route: "^.+\\.(jpg|png)$"
    headers:
      Cache-Control: 'public, max-age=86400'
  - route: "^.+\\.(html|json)$"
    headers:
      Cache-Control: 'no-cache'
